[theme]
primaryColor = "#006AFF"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
